env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
- react
rules:
  indent: 0
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - never
  no-console: 0
  no-unused-vars: 0
  dot-location:
  - error
  - property
globals:
  _testColors: true
